### ISSUE TITLE
Wrong plot labeling in MibiImage_Tutorial notebook

### ISSUE THREAD

**Issue by mapazarr** [ionpath/mibitracker-client#33]
The titles of the plots in the image visualization section are wrong:

In the RGB image:
 - Keratin is red (correct).
 - dsDNA is green but is labeled as blue.
 - CD45 is blue but is labeled as green.

In the CYM image:
 - Keratin is cyan (correct).
 - dsDNA is yellow but is labeled as magenta.
 - CD45 is magenta but is labeled as yellow.

In the 4 channel image:
 - The cyan label is assigned to CD3, but it should be CD4.

The notebook screenshot below depicts the mix-up of the labels:

![image_nb](https://user-images.githubusercontent.com/11326731/58533142-85babd80-819c-11e9-90e9-57324eb80928.png)

**Comment by mapazarr** [comment]
The title of the right-side plot on the second image of the image manipulation section is also wrong:

 - the green label is assigned to CD45 but it should be CD8.

The notebook screenshot below depicts the mix-up of the label:

![image_nb_2](https://user-images.githubusercontent.com/11326731/58681969-a82b1300-8323-11e9-84ec-b2fb59b23208.png)

**Comment by YubinXie** [comment]
I also noticed this issue.
