### ISSUE TITLE
 'MibiRequests' object has no attribute 'get_mibi_image'

### ISSUE THREAD

**Issue by YubinXie** [ionpath/mibitracker-client#60]
Hi MIBI tracker client developer,

Somehow the get_mibi_image no longer works on one of my laptops. Is there an update on the command? Thanks!

**Comment by rfinck** [comment]
Hi @YubinXie , can you please let us know the following:

- from where (conda or virtual environment, directory location, etc.) are you executing this code? please provide a full description of how we could try to reproduce this.
- how did you install, by `git clone` or by `pip install`? If by git, please copy paste the output of  `git describe --tags --long --dirty` from inside the mibitracker-client folder. If by pip, please copy-paste the output of `pip show mibitracker-client`.

**Comment by YubinXie** [comment]
Could this be Python3.6, Python 3.7 issue?
```
Name: mibitracker-client
Version: 1.0
Summary: Python utilities for IONpath MIBItracker and MIBItiff data
Home-page: https://github.com/ionpath/mibitracker-client
Author: IONpath, Inc.
Author-email: mibitracker-support@ionpath.com
License: GNU General Public License v3.0
Location: /Users/xiey/miniconda3/lib/python3.6/site-packages
Requires: requests, pip, numpy, pandas, scikit-image
Required-by: 
```

**Comment by rfinck** [comment]
I suspect it's an environment or path issue. For that we need to know from where you are executing this code. It looks like you've installed it in your base conda environment, but what are the exact steps you take to see those errors? Running a script or in an interactive console? In what directory? Please share steps to reproduce, thanks.

**Comment by YubinXie** [comment]
It was in Jupyter notebook and yes, I installed in base conda environment. 

I will try to create a new environment for it and try again.

**Comment by rfinck** [comment]
Before you create a new environment, when you saw `'MibiRequests' object has no attribute 'get_mibi_image'`, what was the code before that?

**Comment by YubinXie** [comment]
It is 
```
mr = MibiRequests(BACKEND_URL, email, password)    
im = mr.get_mibi_image(image_id)
```

It works on one of my computers.

**Comment by rfinck** [comment]
@YubinXie Did you try to re-install? I can't be 100% sure but I do think this is a path or environment issue.

**Comment by YubinXie** [comment]
sorry @rfinck I have not gotten a chance to try on my laptop since I am working on desktop recently. I will try to have a look tonight.

**Comment by YubinXie** [comment]
@rfinck I  created a new environment based on method 1 in your repo. Interesting, i do not think the mibitracker installation is done by method 1... mibi tracker clinent is not in the environment yml file... Can you check?

**Comment by YubinXie** [comment]
After creating a new conda environment and installation with pip. Now it works.
