### ISSUE TITLE
Can mibitracker-client visualization works with the Json profile from MIBI tracker?

### ISSUE THREAD

**Issue by YubinXie** [ionpath/mibitracker-client#64]
Hi I am trying to tune the visualization profile from MIBI tracker and then visualize the image in local with the same color profile. Is there a quick way to do this? Thanks!

**Comment by rfinck** [comment]
Yes! Use `mibidata.color` -- there's an example about midway down the notebook here: https://github.com/ionpath/mibitracker-client/blob/master/MibiImage_Tutorial.ipynb
and more documentation here:
https://ionpath.github.io/mibitracker-client/mibidata.html#mibidata.color.composite

**Comment by YubinXie** [comment]
I check the content in the json file and the composite function. They do not seem match. For example, in the Json file, it has blur, brightness information:
        "channels": {
            "CD8": {
                "blur": 0,
                "brightness": 0.55,
                "channel": "CD8",
                "color": "Yellow",
                "hex": "#FFFF00",
                "intensity_higher": 15,
                "intensity_lower": 1
            },

However, for the composite function, it only takes gamma, and min_scale...

**Comment by rfinck** [comment]
Yes, I realized that right after my first comment and edited it above to say that we'll add an example of mapping from the json shortly. It's a good question and we should have it in there.

**Comment by YubinXie** [comment]
Sounds great. Thank you!

**Comment by YubinXie** [comment]
@rfinck 
one more thing, gray color is missing from color composite when I compare the color choice in MIBI tacker and MIBI client. I'd like to use gray as an option in MIBI client color composite...

**Comment by rfinck** [comment]
Got it -- thanks for the heads up, it needs to be handled a little differently but we can add it in.

**Comment by rfinck** [comment]
@YubinXie Code is in, we haven't issued a new release yet so you might need to git clone/pull to get the function that you can see here: https://github.com/ionpath/mibitracker-client/blob/master/mibidata/color.py#L230

**Comment by YubinXie** [comment]
Sorry for the late reply. This function works on the MIBI tracker color profile! Thanks!

Though the composite function still has no 'Gray' option. Will it be possible to add it? Thanks!

**Comment by rfinck** [comment]
Hi Yubin,
Glad to hear you're using it!
The previous change addressed making the json file work including any 'Gray' channels there, but I just added 'Gray' to the accepted list in #86. If you've got additional requests, feel free to open up a new issue!
