### ISSUE TITLE
Option A installation actually does not install this client

### ISSUE THREAD

**Issue by YubinXie** [ionpath/mibitracker-client#79]
Hi,
I noticed that in the Option A installation solution, none of the steps installs the client itself. It would be nice to add a line to install the package itself. I believe it would be something like python setup.py install

**Comment by rfinck** [comment]
Thanks @YubinXie for the comment and apologies for the slow reply. That behavior is as intended; if you want to install into an environment please use pip, but if you want to clone the repo and create a development environment please use git. We will update the documentation to make this clearer.
